[
  {
    "remarks": "🇺🇸 USA 192.223.24.121 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "192.223.24.121",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 74.91.126.205 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "74.91.126.205",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 74.91.117.168 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "74.91.117.168",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 74.91.124.187 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "74.91.124.187",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 173.208.245.5 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "173.208.245.5",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 173.208.245.3 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "173.208.245.3",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 104.153.109.173 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "104.153.109.173",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇸 USA 74.91.112.207 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "74.91.112.207",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇬🇧 UK 109.169.22.75 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "109.169.22.75",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇬🇧 UK 88.150.154.27 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "88.150.154.27",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇬🇧 UK 109.169.22.73 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "109.169.22.73",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇬🇧 UK 88.150.154.17 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "88.150.154.17",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇳🇱 NL 85.17.179.81 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "85.17.179.81",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇳🇱 NL 213.109.147.164 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "213.109.147.164",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇳🇱 NL 85.17.179.80 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "85.17.179.80",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇷🇴 Romania 86.107.179.238 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "86.107.179.238",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇨🇭 Switzerland 2.59.219.246 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "2.59.219.246",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇩🇪 Germany 88.198.133.4 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "88.198.133.4",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇪🇸 Spain 212.46.38.55 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "212.46.38.55",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇱🇻 Latvia 185.176.220.20 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "185.176.220.20",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇲🇾 Malaysia 111.90.149.156 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "111.90.149.156",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇮🇹 Italy 195.54.160.133 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "195.54.160.133",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇸🇪 Sweden 46.246.92.174 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "46.246.92.174",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇵🇹 Portugal 185.231.233.125 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "185.231.233.125",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇷🇺 Russia 188.127.235.88 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "188.127.235.88",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇨🇦 Canada 149.56.182.1 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "149.56.182.1",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇨🇦 Canada 198.50.251.184 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "198.50.251.184",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇫🇷 France 51.159.183.5 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "51.159.183.5",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇵🇱 Poland 51.38.137.6 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "51.38.137.6",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇮🇳 India 31.59.184.60 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "31.59.184.60",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇯🇵 Japan 96.62.214.230 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "96.62.214.230",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇭🇰 HongKong 103.253.43.171 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "103.253.43.171",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇸🇬 Singapore 15.235.142.145 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "15.235.142.145",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇦🇺 Australia 139.99.238.43 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "139.99.238.43",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇧🇷 Brazil 157.254.54.34 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "157.254.54.34",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇱🇺 Luxembourg 92.38.162.66 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "92.38.162.66",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇲🇩 Moldova 195.178.106.219 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "195.178.106.219",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇺🇦 Ukraine 193.169.240.43 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "193.169.240.43",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  },
  {
    "remarks": "🇦🇷 Argentina 181.13.218.82 🔌 3129",
    "log": {
      "loglevel": "warning"
    },
    "inbounds": [
      {
        "tag": "socks",
        "port": 10808,
        "protocol": "socks",
        "settings": {
          "auth": "noauth",
          "udp": true,
          "userLevel": 8
        },
        "sniffing": {
          "enabled": true,
          "destOverride": [
            "http",
            "tls"
          ],
          "routeOnly": false
        }
      }
    ],
    "outbounds": [
      {
        "tag": "proxy",
        "protocol": "http",
        "settings": {
          "servers": [
            {
              "address": "181.13.218.82",
              "port": 3129,
              "level": 8,
              "users": [
                {
                  "user": "M_YOU_D",
                  "pass": "Private",
                  "level": 8
                }
              ]
            }
          ]
        },
        "streamSettings": {
          "network": "tcp"
        },
        "mux": {
          "enabled": false,
          "concurrency": -1,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "direct",
        "protocol": "freedom",
        "settings": {
          "domainStrategy": "UseIP"
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      },
      {
        "tag": "block",
        "protocol": "blackhole",
        "settings": {
          "response": {
            "type": "http"
          }
        },
        "mux": {
          "enabled": false,
          "concurrency": 8,
          "xudpConcurrency": 8,
          "xudpProxyUDP443": ""
        }
      }
    ],
    "dns": {
      "servers": [
        "1.1.1.1"
      ],
      "hosts": {
        "domain:googleapis.cn": "googleapis.com",
        "dns.alidns.com": [
          "223.5.5.5",
          "223.6.6.6",
          "2400:3200::1",
          "2400:3200:baba::1"
        ],
        "one.one.one.one": [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001"
        ],
        "dot.pub": [
          "1.12.12.12",
          "120.53.53.53"
        ],
        "dns.google": [
          "8.8.8.8",
          "8.8.4.4",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ],
        "dns.quad9.net": [
          "9.9.9.9",
          "149.112.112.112",
          "2620:fe::fe",
          "2620:fe::9"
        ],
        "common.dot.dns.yandex.net": [
          "77.88.8.8",
          "77.88.8.1",
          "2a02:6b8::feed:0ff",
          "2a02:6b8:0:1::feed:0ff"
        ]
      }
    },
    "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "1.1.1.1"
          ],
          "outboundTag": "proxy",
          "port": "53"
        },
        {
          "type": "field",
          "ip": [
            "223.5.5.5"
          ],
          "outboundTag": "direct",
          "port": "53"
        }
      ]
    }
  }
]
